Add empty dependencies list to metadata.json
This is apparently required. Not having it causes this compilation
error:
puppet parser validate instance.pp
Error: No dependencies module metadata provided for facts